version: '3.8'

services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
